---
openapi: 3.0.3
info:
  title: OpenAPI Documentation
  version: 7.7.7
servers: []
paths:
  "/example_mode_roda":
    get:
      summary: GET /example_mode_roda
      responses:
        '200':
          description: it second roda example
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                required:
                - status
              examples:
                first_roda_example:
                  summary: first roda example
                  value:
                    status: roda_example
                second_roda_example:
                  summary: second roda example
                  value:
                    status: roda_example
  "/roda":
    post:
      summary: Create roda resource
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
              - id
            example:
              id: 1
      responses:
        '200':
          description: when id is given it returns 200
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                required:
                - id
                - name
              example:
                id: 1
                name: hello
  "/tags_roda":
    post:
      summary: POST /tags_roda
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                names:
                  type: array
                  items:
                    type: string
                priority:
                  type: integer
              required:
              - names
              - priority
            example:
              names:
              - roda
              - ruby
              - rack
              priority: 2
      responses:
        '200':
          description: it creates tags with array of strings
          content:
            application/json:
              schema:
                type: object
                properties:
                  created:
                    type: boolean
                  tags:
                    type: array
                    items:
                      type: string
                required:
                - created
                - tags
              example:
                created: true
                tags:
                - roda
                - ruby
                - rack
